title: Data Thoughts
logo: /assets/img/https://github.com/oswald-code/Oswald-portifolio/blob/e99e36e3d35f2d12531206a8045db25ddfed2017/headshot.png
description: Data analyst
#show_downloads: true 
theme: jekyll-theme-minimal
